### ISSUE TITLE
Save Interval lag blocks server & all clients

### ISSUE THREAD

**Issue by wovencode** [vis2k/uMMORPG#43]
Happens on all vis2k assets

You can try this out of the box, we also encountered the issue on the community tests in the past.

With several people online, the save interval causes lag on the server as well as on all connected clients. The lag is noticeable and puts the whole system (including the network) into noticeable stasis.

This is a unbearable situation in a live project and it does not require many connected users to make it noticeable (2+ dozens of players are enough already).

It gets worse with AddOns as this increases the data that must be saved. Its good enough for testing with a few players but not good enough for anything beyond that.

**Comment by blinkuz** [comment]
Can you share with the features on the server I test? The truth is, this is a bit troubling.

**Comment by vis2k** [comment]
so openmmo failed and now you came back to troll.
got it.

**Comment by jonmalave** [comment]
@vis2k why are you closing issue that have not be resolved yet???? seriously what is your deal

**Comment by iamallama** [comment]
@jonmalave It was closed because A) fhiz and you are trolling, spamming and just talking crap. Fhiz knows about this issue and knows how to use a background thread for queries which completely mitigates the issue as evidenced by doing exactly that in his old addon pack. And B) it has been improved quite a lot recently with around a 10x speed up by using a different library for sqlite. I wonder if either of you even tested with the most recent version.

**Comment by wovencode** [comment]
@iamallama Im actually not talking crap at all. Saving lags with two dozens or more players online. If I remember right you where with us when we did the community test, so you saw yourself. Its just a matter of fact that its not fixed until today.

But its ok, the assets dead anyway.

**Comment by iamallama** [comment]
@wovencode and yet we haven't had a community test since the database connector was changed over 6 months ago giving around a 10x improvement to database saving. Have you even tried a current version? So yes, I would say you are just talking crap.
